name: ci
"on":
  - push
  - pull_request
jobs:
  test:
    name: Node ${{ matrix.node }}
    runs-on: self-hosted
    environment: ci
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node:
          - "18"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install playwright browsers (only needed for WebkitHeadless)
        run: npx playwright install --with-deps
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test
